Repository OpenPerpetuum/perpetuum-killboard, pull requests merged in 2021-03, with the labels that each got.

#7 Darkmode + smarter/new icon lookup
  package-lock.json
  src/App.js
  src/Victim.css
  src/iconResolve.js
  src/index.css
Labels: enhancement

#11 Css classes for darkmode styles
  src/App.js
  src/Victim.js
  src/index.css
Labels: bug

#12 Extract components from App
  src/App.js
  src/components/Attacker.js
  src/components/Attackers.js
  src/components/FooterSection.js
  src/components/HeroSection.js
  src/components/KillBoard.js
  src/components/KillDetail.js
  src/components/Victim.js
  src/components/Victims.js
  src/css/App.css
  src/css/Victim.css
  src/css/index.css
  src/index.js
Labels: refactor
